const TABS=[["eng","Engineering"],["state","State CETs"],["def","Defence"],["sci","Science & maths"],["des","Design & architecture"],["law","Law"],["mgt","Management"],["comp","Computing"]];
const CATNAME=Object.fromEntries(TABS);
const GROUPS=["Oct 2026","Oct–Nov 2026","Nov 2026","Dec 2026","Dec 2026 – Jan 2027","Jan–Feb 2027","Feb 2027","Feb–Mar 2027","Mar 2027","Mar–Apr 2027","Apr 2027","Apr–Jun 2027","May–Jun 2027","Jun–Jul 2027"];

/* st: c confirmed, m exam date confirmed and form expected, e expected */
const CAL=[
{sn:"CLAT",as:"31 Oct",es:"6 Dec",g:0,n:"CLAT 2027",cat:"law",a:"3 Aug – 31 Oct 2026",e:"6 Dec 2026, 2–4 PM, offline",st:"c",ex:"clat"},
{sn:"UCEED",as:"31 Oct",es:"17 Jan",g:0,n:"UCEED 2027",cat:"des",a:"1–31 Oct 2026. Late fee to 6 Nov, 5 PM",e:"17 Jan 2027, 9 AM–12 noon",st:"c",ex:"uceed"},
{sn:"JEE Main · S1",as:"~Nov",es:"22–30 Jan",g:1,n:"JEE Main 2027 Session 1",cat:"eng",a:"Expected to open in the last week of Oct, close in Nov",e:"22–24 and 28–30 Jan 2027 (31 Jan buffer)",st:"m"},
{sn:"AILET",as:"10 Nov",es:"13 Dec",g:2,n:"AILET 2027",cat:"law",a:"7 Aug – 10 Nov 2026",e:"13 Dec 2026, 2–4 PM, offline",st:"c",ex:"ailet"},
{sn:"NID DAT",as:"30 Nov",es:"20 Dec",g:2,n:"NID DAT 2027",cat:"des",a:"10 Sep – 30 Nov 2026. Edit window 1–3 Dec",e:"Prelims 20 Dec 2026",st:"c",ex:"nid"},
{sn:"KLEEE",as:"2 Dec",es:"See KL site",g:3,n:"KLEEE 2027 (KL University)",cat:"eng",a:"18 Sep – 2 Dec 2026, first phase (reported by an aggregator)",e:"Per KL schedule. Verify on kluniversity.in",st:"e"},
{sn:"NDA & NA (I)",as:"22 Dec",es:"11 Apr",g:3,n:"NDA & NA (I) 2027",cat:"def",a:"2–22 Dec 2026",e:"11 Apr 2027 (Sun)",st:"c",ex:"nda"},
{sn:"NIFT",as:"~Dec",es:"10 Jan",g:4,n:"NIFT 2027",cat:"des",a:"Expected Nov–Dec 2026",e:"10 Jan 2027 (NTA calendar)",st:"m",ex:"nift"},
{sn:"KEAM",as:"~Feb",es:"~Apr",g:5,n:"KEAM 2027",cat:"state",a:"2026 ref: 5 Jan – 31 Jan/6 Feb",e:"2026 ref: 17–23 Apr, CBT",st:"e",ex:"keam"},
{sn:"CUET-UG",as:"~Feb",es:"~May–Jun",g:6,n:"CUET-UG 2027",cat:"sci",a:"Expected to open Jan 2027, close Feb (2026 opened 3 Jan)",e:"Expected May–Jun 2027",st:"e",ex:"cuet"},
{sn:"MHT CET",as:"~Feb",es:"~Apr–May",g:6,n:"MHT CET 2027",cat:"state",a:"2026 ref: 10 Jan – 24 Feb. Late fee to 27 Feb",e:"2026 ref: PCM 11–20 Apr and 12–21 May",st:"e",ex:"mht"},
{sn:"KCET",as:"~Feb",es:"~Apr",g:6,n:"KCET 2027",cat:"state",a:"2026 ref: about 16 Jan – 27 Feb",e:"2026 ref: 23–24 Apr",st:"e",ex:"kcet"},
{sn:"JEE Main · S2",as:"~Feb",es:"~Apr",g:7,n:"JEE Main 2027 Session 2",cat:"eng",a:"Expected Feb 2027",e:"Expected Apr 2027",st:"e"},
{sn:"MET · P1",as:"~Mar",es:"~Apr–May",g:8,n:"MET 2027, Phase 1 (Manipal)",cat:"eng",a:"Expected to open late Sep or early Oct 2026. Phase 1 closes in the 3rd week of Mar",e:"Expected Apr (Phase 1), May (Phase 2)",st:"e",ex:"met"},
{sn:"COMEDK",as:"~Mar",es:"~May",g:8,n:"COMEDK UGET 2027",cat:"eng",a:"Expected Feb to 3rd week of Mar",e:"Expected 2nd week of May",st:"e",ex:"comedk"},
{sn:"ISI",as:"~Mar",es:"~May",g:8,n:"ISI Admission Test 2027",cat:"sci",a:"2026 ref: 12 Feb – 26 Mar (extended)",e:"2026 ref: 10 May",st:"e",ex:"isi"},
{sn:"IPMAT Indore",as:"~Mar",es:"~May",g:8,n:"IPMAT Indore 2027",cat:"mgt",a:"2026 ref: 2 Feb – 17 Mar",e:"2026 ref: 4 May",st:"e",ex:"ipmat"},
{sn:"VITEEE",as:"~Apr",es:"~Apr",g:9,n:"VITEEE 2027",cat:"eng",a:"Expected to open in the last week of Oct 2026. 2026 closed 12 Apr",e:"Expected Apr 2027 (2026: 28 Apr – 3 May)",st:"e",ex:"viteee"},
{sn:"BITSAT · S1",as:"~Mar–Apr",es:"~Apr–May",g:9,n:"BITSAT 2027, Session 1",cat:"eng",a:"Expected Dec 2026 or Jan 2027 to Mar/Apr 2027",e:"Expected Apr–May 2027",st:"e",ex:"bitsat"},
{sn:"AP EAPCET",as:"~Mar",es:"~May",g:9,n:"AP EAPCET 2027",cat:"state",a:"2026 ref: 4 Feb – 24 Mar. Late fee to 10 Apr",e:"2026 ref: Engg 12–15 and 18 May",st:"e",ex:"apeapcet"},
{sn:"TG EAPCET",as:"~Apr",es:"~May",g:10,n:"TG EAPCET 2027",cat:"state",a:"2026 ref: 19 Feb – 4 Apr. Late fees to 2 May",e:"2026 ref: Engg 9–11 May",st:"e",ex:"tgeapcet"},
{sn:"WBJEE",as:"~Apr",es:"~May",g:10,n:"WBJEE 2027",cat:"state",a:"2026 ref: 10 Mar – 8 Apr",e:"2026 ref: 24 May",st:"e",ex:"wbjee"},
{sn:"IISER IAT",as:"~Apr",es:"~Jun",g:10,n:"IISER IAT 2027",cat:"sci",a:"2026 ref: 5 Mar – 13 Apr",e:"2026 ref: 7 Jun",st:"e",ex:"iat"},
{sn:"NEST",as:"~Apr",es:"~Jun",g:10,n:"NEST 2027",cat:"sci",a:"2026 ref: 5 Jan – 8 Apr",e:"2026 ref: 6 Jun",st:"e",ex:"nest"},
{sn:"IPMAT Rohtak",as:"~Apr",es:"~May",g:10,n:"IPMAT Rohtak 2027",cat:"mgt",a:"2026 ref: 6 Feb – 6 Apr",e:"2026 ref: 10 May",st:"e",ex:"ipmatr"},
{sn:"SRMJEEE · P1",as:"~Apr",es:"~Apr",g:10,n:"SRMJEEE 2027, Phase 1",cat:"eng",a:"Expected late Oct or Nov 2026 to mid-Apr 2027",e:"Expected late Apr 2027",st:"e",ex:"srm"},
{sn:"NATA",as:"~Mar",es:"~Apr–Jun",g:11,n:"NATA 2027",cat:"des",a:"Expected from Mar 2027",e:"Expected Apr–Jun, Fri and Sat. Phase 2 around Aug",st:"e",ex:"nata"},
{sn:"BITSAT · S2",as:"~May",es:"~May–Jun",g:12,n:"BITSAT 2027, Session 2",cat:"eng",a:"Expected Apr–May 2027",e:"Expected May–Jun 2027",st:"e",ex:"bitsat"},
{sn:"NDA & NA (II)",as:"~Jun",es:"~Sep",g:12,n:"NDA & NA (II) 2027",cat:"def",a:"Expected late May to mid-Jun (2026: 20 May – 11 Jun)",e:"Expected Sep 2027 (2026: 13 Sep)",st:"e",ex:"nda"},
{sn:"Navy 10+2",as:"~Jun",es:"~Sep",g:12,n:"Navy 10+2 B.Tech, Jan 2028 course",cat:"def",a:"Expected May–Jun 2027 (2026: 29 May – 18/29 Jun). Uses the JEE Main 2027 rank",e:"SSB from about Sep 2027",st:"e",ex:"navy"},
{sn:"SRMJEEE · P2–3",as:"~Jun",es:"~Jun–Jul",g:13,n:"SRMJEEE 2027, Phases 2 and 3",cat:"eng",a:"Expected Jun 2027",e:"Expected Jun–Jul 2027",st:"e",ex:"srm"}
];

const TICKETS=[
{n:"JEE Main 2027",sub:"Session 1 registration",kind:"w",big:"Late Oct",unit:"expected to open",close:"Expected in Nov",exam:"22–24, 28–30 Jan",url:"https://jeemain.nta.nic.in",host:"jeemain.nta.nic.in"},
{eid:"clat",n:"CLAT 2027",sub:"Law · 5-year BA LLB",kind:"c",due:"2026-10-31T23:59:00+05:30",close:"31 Oct 2026",exam:"6 Dec 2026",url:"https://consortiumofnlus.ac.in",host:"consortiumofnlus.ac.in"},
{eid:"uceed",n:"UCEED 2027",sub:"Design · IIT B.Des",kind:"c",due:"2026-10-31T23:59:00+05:30",close:"31 Oct (late fee to 6 Nov)",exam:"17 Jan 2027",url:"https://www.uceed.iitb.ac.in",host:"uceed.iitb.ac.in"},
{eid:"ailet",n:"AILET 2027",sub:"Law · NLU Delhi",kind:"c",due:"2026-11-10T23:59:00+05:30",close:"10 Nov 2026",exam:"13 Dec 2026",url:"https://nationallawuniversitydelhi.in",host:"nationallawuniversitydelhi.in"},
{eid:"nid",n:"NID DAT 2027",sub:"Design · B.Des at NID",kind:"c",due:"2026-11-30T23:59:00+05:30",close:"30 Nov 2026",exam:"Prelims 20 Dec",url:"https://admissions.nid.edu",host:"admissions.nid.edu"},
{eid:"nda",n:"NDA & NA (I) 2027",sub:"Defence · UPSC",kind:"c",due:"2026-12-22T23:59:00+05:30",open:"2026-12-02T00:00:00+05:30",close:"22 Dec 2026 (opens 2 Dec)",exam:"11 Apr 2027",url:"https://upsc.gov.in",host:"upsc.gov.in"}
];
const PCM="Class 11–12 NCERT Physics, Chemistry and Maths. See the shared syllabus under Syllabus.";
const EX=[
/* ENGINEERING */
{id:"bitsat",cat:"eng",sort:9,n:"BITSAT",full:"Birla Institute of Technology & Science Admission Test",body:"BITS Pilani",st:"e",
 leads:"BE, B.Pharm and integrated M.Sc. at the Pilani, Goa and Hyderabad campuses.",
 elig:"Class 12 with PCM (PCB for B.Pharm). 75% aggregate in PCM with at least 60% in each subject. 2026 pass-outs or 2027 appearing. No age limit. Re-taking all Class 12 subjects makes you ineligible.",
 pattern:"CBT, 3 hours, 130 questions: Physics 30, Chemistry 30, English 10, Logical Reasoning 20, Maths 40. +3/−1, maximum 390. 12 bonus questions unlock if you finish all 130 without changing answers.",
 syl:PCM+" Extras: English proficiency (grammar, vocabulary, reading comprehension, composition) and logical reasoning (analogy, classification, series, pattern perception, mirror images).",
 portal:["bitsadmission.com","https://bitsadmission.com"],
 apply:"Not announced. Expected notification Dec 2026 – Jan 2027, forms closing Mar/Apr 2027.",
 exam:"Expected Apr–May (Session 1) and May–Jun 2027 (Session 2).",fee:"See the brochure.",
 note:"Two sessions. Register for both and the better score counts. Admission is by score through iterations, not counselling."},
{id:"viteee",cat:"eng",sort:9,n:"VITEEE",full:"VIT Engineering Entrance Examination",body:"VIT",st:"e",
 leads:"VIT Vellore, Chennai, AP (Amaravati) and Bhopal.",
 elig:"PCM or PCB with 60% aggregate (50% for SC/ST and candidates from J&K, Ladakh and the North-East). Age cut-off about 20 years. Verify the date-of-birth limit in the 2027 brochure.",
 pattern:"CBT, 2.5 hours, 125 MCQs: Maths/Biology 40, Physics 35, Chemistry 35, Aptitude 10, English 5. No negative marking.",
 syl:PCM+" Extras: aptitude and English.",
 portal:["viteee.vit.ac.in","https://viteee.vit.ac.in"],
 apply:"Expected to open in the last week of Oct 2026, closing Mar–Apr 2027. In 2026 forms opened 24 Oct 2025 and closed 12 Apr 2026.",
 exam:"Expected Apr 2027. In 2026: 28 Apr – 3 May.",fee:"See the brochure.",note:"Slot booking opens in early April."},
{id:"srm",cat:"eng",sort:10,n:"SRMJEEE",full:"SRM Joint Engineering Entrance Examination",body:"SRM Institute of Science and Technology",st:"e",
 leads:"SRMIST Kattankulathur, Ramapuram, Vadapalani, Delhi-NCR and Tiruchirappalli. SRM AP and SRM Sonepat use the same exam.",
 elig:"PCM (Biology accepted for biotech-type branches). Sources differ on the minimum: 50% or 60% in PCM. Reported age rule: at least 16 years 6 months by 31 Jul 2027.",
 pattern:"Online, remote-proctored from home. About 2.5 hours, 125 questions: Physics 40, Chemistry 35, Maths 40, English 5, Aptitude 10. No negative marking.",
 syl:PCM+" Extras: aptitude and English.",
 portal:["srmist.edu.in","https://www.srmist.edu.in"],
 apply:"Expected to open late Oct or Nov 2026, Phase 1 closing mid-Apr 2027. In 2025 forms opened 12 Nov 2024.",
 exam:"Expected Phase 1 late Apr, Phase 2 Jun, Phase 3 Jul 2027.",fee:"₹1,400 per phase (reported).",
 note:"Each phase needs its own form. The best score is used."},
{id:"met",cat:"eng",sort:8,n:"MET",full:"Manipal Entrance Test",body:"MAHE Manipal",st:"e",
 leads:"MIT Manipal, MIT Bengaluru, Manipal University Jaipur, SMIT Sikkim and MAHE Dubai, through one common application.",
 elig:"Class 12 with Physics, Maths and English compulsory, plus Chemistry, Biotechnology, Biology or a technical vocational subject. 50% aggregate in PCM (verify in the 2027 brochure).",
 pattern:"CBT, about 2 hours: Physics, Chemistry, Maths and English/general aptitude. MAHE has changed question counts in recent years, so use the 2027 brochure.",
 syl:PCM+" Extras: English and general aptitude.",
 portal:["manipal.edu","https://www.manipal.edu"],
 apply:"Expected to open late Sep or early Oct 2026. Phase 1 closes in the 3rd week of Mar 2027, Phase 2 in the 4th week of Apr. As of 28 Sep the link was not yet active, so check daily.",
 exam:"Phase 2 expected in the last week of May 2027. In 2026: 23–24 May.",fee:"See the brochure."},
{id:"comedk",cat:"eng",sort:8,n:"COMEDK UGET",full:"Consortium of Medical, Engineering and Dental Colleges of Karnataka",body:"COMEDK",st:"e",
 leads:"About 190 private engineering colleges in Karnataka (RVCE, BMSCE, MSRIT, PES and others). Open to students from all states.",
 elig:"PCM with 45% (40% for SC/ST/OBC of Karnataka).",
 pattern:"CBT, 3 hours, 180 MCQs, 60 each in Physics, Chemistry and Maths. 1 mark each. No negative marking.",
 syl:PCM,portal:["comedk.org","https://www.comedk.org"],
 apply:"Expected: notification early Jan 2027, registration Feb to the 3rd week of Mar.",
 exam:"Expected 2nd week of May 2027. Past exams: 12 May 2024, 10 and 25 May 2025, 9 May 2026.",fee:"See the brochure."},

/* STATE CETs */
{id:"mht",cat:"state",sort:6,n:"MHT CET",full:"Maharashtra Common Entrance Test",body:"State CET Cell, Maharashtra",st:"e",
 leads:"Engineering seats in Maharashtra.",elig:"See the CET Cell brochure.",
 pattern:"CBT, 3 hours. Maths 50 questions (2 marks each), Physics 50 and Chemistry 50 (1 mark each). No negative marking. 2026 was the first year with two attempts.",
 syl:"Mostly Class 12 with some Class 11 topics.",portal:["cetcell.mahacet.org","https://cetcell.mahacet.org"],
 apply:"2026 ref: 10 Jan – 24 Feb, late fee to 27 Feb. Sources give 12, 15 or 24 Feb as the close, so verify.",
 exam:"2026 ref: PCM 11–20 Apr and 12–21 May. Result 16 Jun.",fee:"See the brochure."},
{id:"kcet",cat:"state",sort:6,n:"KCET",full:"Karnataka Common Entrance Test",body:"Karnataka Examinations Authority",st:"e",
 leads:"Government and quota engineering seats in Karnataka.",elig:"See the KEA brochure.",
 pattern:"Pen and paper. 60 questions per subject, 80 minutes each. No negative marking. Rank is 50% CET plus 50% board PCM marks.",
 syl:PCM,portal:["cetonline.karnataka.gov.in/kea","https://cetonline.karnataka.gov.in/kea"],
 apply:"2026 ref: about 16 Jan – 27 Feb.",exam:"2026 ref: 23–24 Apr (Kannada test 22 Apr). Result 6 Jun.",fee:"See the brochure."},
{id:"wbjee",cat:"state",sort:10,n:"WBJEE",full:"West Bengal Joint Entrance Examination",body:"WBJEEB",st:"e",
 leads:"Engineering seats in West Bengal.",elig:"See the WBJEEB brochure.",
 pattern:"OMR. Paper I Maths 11:00–13:00, Paper II Physics and Chemistry 14:00–16:00. Category-wise marking with negative marks on single-correct questions.",
 syl:PCM,portal:["wbjeeb.nic.in","https://wbjeeb.nic.in"],
 apply:"2026 ref: 10 Mar – 8 Apr.",exam:"2026 ref: 24 May.",fee:"See the brochure."},
{id:"apeapcet",cat:"state",sort:9,n:"AP EAPCET",full:"Andhra Pradesh Engineering, Agriculture & Pharmacy CET",body:"JNTU Kakinada for APSCHE",st:"e",
 leads:"Engineering seats in Andhra Pradesh.",elig:"See the APSCHE brochure.",
 pattern:"CBT, 160 questions (Maths 80, Physics 40, Chemistry 40), 3 hours. No negative marking.",
 syl:PCM,portal:["cets.apsche.ap.gov.in","https://cets.apsche.ap.gov.in"],
 apply:"2026 ref: from 4 Feb, deadline reported as 24 Mar, late fee to 10 Apr.",exam:"2026 ref: Engineering 12–15 and 18 May.",fee:"See the brochure."},
{id:"tgeapcet",cat:"state",sort:10,n:"TG EAPCET",full:"Telangana Engineering, Agriculture & Pharmacy CET",body:"JNTU Hyderabad for TGCHE",st:"e",
 leads:"Engineering seats in Telangana.",elig:"See the TGCHE brochure.",
 pattern:"CBT, 160 questions, 3 hours. No negative marking.",
 syl:PCM,portal:["eapcet.tgche.ac.in","https://eapcet.tgche.ac.in"],
 apply:"2026 ref: 19 Feb – 4 Apr. Late fees from ₹250 to ₹10,000 up to 2 May.",exam:"2026 ref: Engineering 9–11 May.",fee:"See the brochure."},
{id:"keam",cat:"state",sort:5,n:"KEAM",full:"Kerala Engineering Architecture Medical",body:"CEE Kerala",st:"e",
 leads:"Engineering seats in Kerala.",elig:"See the CEE prospectus.",
 pattern:"CBT, 2–5 PM. Physics, Chemistry, Maths. Negative marking applies; verify in the 2027 prospectus. Centres include Delhi, Mumbai, Chennai, Bengaluru and the UAE.",
 syl:PCM,portal:["cee.kerala.gov.in","https://cee.kerala.gov.in"],
 apply:"2026 ref: 5 Jan – 31 Jan, extended to 6 Feb.",exam:"2026 ref: 17–23 Apr.",fee:"See the prospectus."},

/* DEFENCE */
{id:"nda",cat:"def",sort:3,n:"NDA & NA",full:"National Defence Academy & Naval Academy Examination",body:"UPSC",st:"c",
 leads:"NDA Khadakwasla (Army, Navy and Air Force wings) and the Indian Naval Academy (10+2 Cadet Entry). A JNU degree and Permanent Commission.",
 elig:"Unmarried Indian citizens. Women eligible since 2021. Age 16.5 to 19.5 on the course start date, with the exact birth-date window in each notification. Army wing: Class 12 any stream. Air Force and Navy wings need Physics and Maths. Class 12 appearing students may apply.",
 pattern:"Offline OMR. Maths 300 marks (120 questions, 2.5 hours). General Ability Test 600 marks (150 questions, 2.5 hours: English 200, General Knowledge 400). One-third negative marking. Then SSB (900 marks) and a medical.",
 syl:"Maths: algebra, matrices and determinants, trigonometry, 2D and 3D analytical geometry, differential calculus, integral calculus and differential equations, vectors, statistics and probability. GAT: English, Physics, Chemistry, general science, history, geography, current events.",
 portal:["upsc.gov.in","https://upsc.gov.in"],
 apply:"NDA (I) 2027: 2–22 Dec 2026. NDA (II) 2027 expected late May to mid-Jun.",
 exam:"NDA (I): 11 Apr 2027. NDA (II): expected Sep 2027.",fee:"₹100. Exempt for SC/ST, female candidates and wards of JCOs/NCOs/ORs.",
 note:"A 2027 Class 12 student gets two attempts in 2027. NDA (I) falls in board-exam season, so start Maths and GAT practice by November. NDA (II) 2026 was held 13 Sep 2026 for 394 vacancies."},
{id:"navy",cat:"def",sort:12,n:"Navy 10+2 B.Tech",full:"Indian Navy 10+2 (B.Tech) Cadet Entry Scheme",body:"Indian Navy",st:"e",
 leads:"A 4-year B.Tech at the Indian Naval Academy, Ezhimala, with a JNU degree and Permanent Commission.",
 elig:"70% aggregate in PCM and 50% in English (Class 10 or 12). Needs the JEE Main rank of the previous calendar year. The Jan 2027 course asked for birth dates 2 Jul 2007 – 1 Jan 2010; verify in each notification.",
 pattern:"No written exam. Shortlisting on the JEE Main CRL, then SSB and a medical.",
 syl:"No separate syllabus. Your JEE Main rank is the entry ticket.",
 portal:["joinindiannavy.gov.in","https://www.joinindiannavy.gov.in"],
 apply:"Nothing to apply for now. A JEE Main 2027 student applies for the Jan 2028 course, notified around May–Jun 2027 (2026: 29 May – 18/29 Jun).",
 exam:"SSB from about Sep 2027.",fee:"None listed.",
 note:"Each course uses the previous year’s JEE Main rank, so a 2027 Class 12 student enters through Jan 2028, not the 2027 courses. The Jan 2027 course had 60 vacancies (30 Mechanical, 30 Electronics & Communication)."}
];
EX.push(
/* SCIENCE & MATHS */
{id:"iat",cat:"sci",sort:10,n:"IISER IAT",full:"IISER Aptitude Test",body:"IISERs (2026: IISER Berhampur organised)",st:"e",
 leads:"5-year BS-MS at IISER Berhampur, Bhopal, Kolkata, Mohali, Pune, Thiruvananthapuram and Tirupati. Also BS in Economic Sciences (Bhopal), Economic & Statistical Sciences (Tirupati), B.Tech at Bhopal and Computational & Data Sciences at Kolkata. IISc Bangalore and IIT Madras also accept IAT scores for some programmes.",
 elig:"Class 12 Science passed in 2024, 2025 or 2026. 60% aggregate for General/OBC/EWS. Sources conflict on SC/ST/PwD (55% or 50%). Maths is mandatory for the economics, data-science and B.Tech programmes. You may attempt in the year of passing and the next two years.",
 pattern:"CBT, 3 hours. Biology, Chemistry, Maths and Physics, 15 questions each (60 in all). +4/−1. All sections must be attempted.",
 syl:"Class 11–12 Physics, Chemistry, Maths and Biology. PCM students must revise Biology basics.",
 portal:["iiseradmission.in","https://www.iiseradmission.in"],
 apply:"2026 ref: 5 Mar – 13 Apr, corrections 13–15 Apr. 2027 expected: notification about Feb, forms Mar–Apr.",
 exam:"2026 ref: 7 Jun, 9 AM–12 PM. 2027 expected late May or Jun.",fee:"See the brochure."},
{id:"nest",cat:"sci",sort:10,n:"NEST",full:"National Entrance Screening Test",body:"NISER and UM-DAE CEBS",st:"e",
 leads:"5-year integrated M.Sc. at NISER Bhubaneswar and UM-DAE CEBS Mumbai. Admitted students get the DAE DISHA scholarship of ₹60,000 a year plus ₹20,000 a year for summer internships (per 2026 brochure summaries). Both institutes can endorse eligible students for INSPIRE-SHE.",
 elig:"Class 12 Science with 60% (55% for SC/ST/PwD; verify). Two-year attempt window.",
 pattern:"CBT, 3 hours. Four sections (Biology, Chemistry, Maths, Physics). The best three count towards the merit list. Mixed single and multiple-correct questions with negative marking on some types.",
 syl:"NCERT Class 11–12 science. Questions are more conceptual than JEE Main.",
 portal:["nestexam.in","https://www.nestexam.in"],
 apply:"2026 ref: 5 Jan – 8 Apr (extended). 2027 expected: forms open Jan.",
 exam:"2026 ref: Sat 6 Jun, 2–5 PM, 387 cities. Result 24 Jun. 2027 expected Jun.",fee:"See the brochure."},
{id:"isi",cat:"sci",sort:8,n:"ISI Admission Test",full:"Indian Statistical Institute, B.Stat and B.Math",body:"ISI",st:"e",
 leads:"B.Stat (Hons) in Kolkata and B.Math (Hons) in Bengaluru.",
 elig:"10+2 with Mathematics and English.",
 pattern:"Offline, two papers. UGA is multiple-choice maths. UGB is descriptive, proof-style maths.",
 syl:"Class 11–12 maths with an olympiad flavour: algebra, inequalities, number theory, combinatorics, functions, calculus, coordinate geometry and trigonometry.",
 portal:["admission.isical.ac.in","https://admission.isical.ac.in"],
 apply:"2026 ref: 12 Feb – 26 Mar (extended from 13 Mar). 2027 expected Feb–Mar.",
 exam:"2026 ref: Sun 10 May. The exam date was announced 29 Dec 2025, so expect the 2027 date around late Dec 2026.",fee:"Very low.",
 note:"Stipend of ₹5,000 a month plus a ₹5,000 yearly contingency grant for B.Stat and B.Math. The full stipend needs an average composite score of at least 60% and 75% attendance. It is halved for 45–60%. The B.Sc. Statistical Data Science programme has a separate portal and later timeline (2026: 20 May – 1 Jul)."},
{id:"cmi",cat:"sci",sort:14,n:"CMI Entrance",full:"Chennai Mathematical Institute",body:"CMI",st:"e",
 leads:"B.Sc (Hons) in Mathematics & Computer Science, or Mathematics & Physics. Among India’s strongest undergraduate maths programmes.",
 elig:"Class 12. Check the CMI brochure.",
 pattern:"Written olympiad-style problem solving. Direct interview or admission options exist for strong INMO performers.",
 syl:"Class 11–12 maths at problem-solving depth. The same preparation serves ISI.",
 portal:["cmi.ac.in","https://www.cmi.ac.in"],
 apply:"Typically Feb–Apr. Verify the 2027 notice.",exam:"Typically May, in many cities. Verify.",fee:"See the brochure."},
{id:"cuet",cat:"sci",sort:6,n:"CUET-UG",full:"Common University Entrance Test",body:"NTA",st:"e",
 leads:"BSc, B.Tech, BA, B.Com and BBA at central universities (DU, BHU, JNU, Jamia, AMU, Hyderabad and others), many state and private universities, and ICAR agricultural universities. ICAR’s separate AIEEA-UG has been folded into CUET.",
 elig:"See the NTA information bulletin.",
 pattern:"Choose up to 5 subjects across Section I (languages), Section II (domain) and Section III (General Aptitude Test). Each paper has 50 compulsory questions in 60 minutes. CBT, +5/−1.",
 syl:"Domain papers (Physics, Chemistry, Mathematics or Applied Maths, Computer Science and others) follow Class 12 NCERT. The General Test covers GK, current affairs, reasoning, numerical ability and quantitative reasoning.",
 portal:["cuet.nta.nic.in","https://cuet.nta.nic.in"],
 apply:"Not announced. Expected to open Jan 2027 and close Feb. 2026 registration opened 3 Jan 2026. Some aggregators project Feb–Mar.",
 exam:"Expected May–Jun 2027.",fee:"See the bulletin.",
 note:"A PCM combination: English + Physics + Chemistry + Mathematics + General Test. It keeps BSc (Hons), some B.Tech, BMS/BBA and economics routes open. Maths is often mandatory for BMS and Economics (Hons)."},

/* DESIGN & ARCHITECTURE */
{id:"uceed",cat:"des",sort:0,n:"UCEED",full:"Undergraduate Common Entrance Examination for Design",body:"IIT Bombay",st:"c",
 leads:"B.Des at IIT Bombay, Delhi, Guwahati, Hyderabad, Indore, Roorkee and IIITDM Jabalpur.",
 elig:"Class 12 passed in 2026 or appearing in 2027. Any stream.",
 pattern:"3 hours. Part A is CBT (NAT, MSQ and MCQ on visualisation, observation, design sensitivity, reasoning and language). Part B is drawing and sketching plus design aptitude.",
 syl:"Visualisation and spatial reasoning, observation, design sensitivity, environmental and social awareness, analytical and logical reasoning, English reading, sketching (perspective, proportion, shading, composition) and basic colour theory.",
 portal:["uceed.iitb.ac.in","https://www.uceed.iitb.ac.in"],
 apply:"1–31 Oct 2026. Late fee until 6 Nov, 5 PM.",
 exam:"17 Jan 2027, 9 AM–12 noon. Admit card 1 Jan. Result 6 Mar. B.Des applications from 15 Mar 2027.",fee:"See the portal."},
{id:"nid",cat:"des",sort:2,n:"NID DAT",full:"National Institute of Design, Design Aptitude Test",body:"NID",st:"c",
 leads:"B.Des and Integrated M.Des at NID Ahmedabad, Gandhinagar, Bengaluru and other NIDs.",
 elig:"Class 12, any stream. Marksheet by 15 Jul 2027.",
 pattern:"Prelims: pen and paper design aptitude (drawing plus objective). Mains: studio test and interview.",
 syl:"Drawing, visualisation, observation and design aptitude, as for UCEED.",
 portal:["admissions.nid.edu","https://admissions.nid.edu"],
 apply:"By 30 Nov 2026, 11:59 PM. Edit window 1–3 Dec.",
 exam:"Prelims 20 Dec 2026 (admit card 10 Dec). Prelims result 16 Mar 2027. Mains to be announced.",fee:"₹3,000 (General/OBC), ₹1,500 (SC/ST/PwD), as reported."},
{id:"nift",cat:"des",sort:4,n:"NIFT",full:"NIFT Entrance Exam",body:"NTA for NIFT",st:"m",
 leads:"B.Des and B.FTech at NIFT campuses.",
 elig:"Class 12, any stream. B.FTech needs PCM.",
 pattern:"GAT (CBT) plus CAT (creative, pen and paper, for B.Des). Then a Situation Test.",
 syl:"General ability, quantitative and communication skills, creative ability and design aptitude.",
 portal:["exams.nta.nic.in/niftee","https://exams.nta.nic.in/niftee"],
 apply:"Expected Nov–Dec 2026. Some sites show a January close, which cannot be right for a 10 Jan exam, so expect December.",
 exam:"10 Jan 2027 (NTA calendar).",fee:"See the bulletin."},
{id:"nata",cat:"des",sort:11,n:"NATA",full:"National Aptitude Test in Architecture",body:"Council of Architecture",st:"e",
 leads:"B.Arch at all CoA-recognised colleges. Required for many state and private seats.",
 elig:"10+2 with Physics and Maths compulsory. 45% aggregate (CoA norm; verify).",
 pattern:"Part A drawing and composition (offline, 90 minutes) plus Part B MCQ aptitude (online, 90 minutes). Total 200. Up to 3 attempts, best score counts.",
 syl:"Drawing, composition, architecture awareness, basic Physics and Maths, general aptitude.",
 portal:["nata.in","https://www.nata.in"],
 apply:"Expected from Mar 2027.",exam:"Expected Apr–Jun 2027 on Fridays and Saturdays. Phase 2 around Aug.",fee:"₹1,750 in 2026."},

/* LAW */
{id:"clat",cat:"law",sort:0,n:"CLAT",full:"Common Law Admission Test",body:"Consortium of NLUs",st:"c",
 leads:"5-year BA LLB at about 24 or more National Law Universities.",
 elig:"Class 12 with 45% (40% for SC/ST). No age limit.",
 pattern:"Offline, 2 hours, 120 questions: English, Current Affairs including GK, Legal Reasoning, Logical Reasoning and Quantitative Techniques. +1/−0.25 (verify).",
 syl:"Five passage-based sections as in the pattern. There is no Class 11–12 syllabus.",
 portal:["consortiumofnlus.ac.in","https://consortiumofnlus.ac.in"],
 apply:"3 Aug – 31 Oct 2026.",exam:"6 Dec 2026, 2–4 PM.",fee:"See the portal.",
 note:"PCM students have an edge in patent, IP and tech law."},
{id:"ailet",cat:"law",sort:2,n:"AILET",full:"All India Law Entrance Test",body:"NLU Delhi",st:"c",
 leads:"BA LLB at NLU Delhi only.",
 pattern:"Offline, 2 hours. English, Current Affairs/GK and Logical Reasoning.",
 syl:"Passage-based reasoning sections as in the pattern.",
 portal:["nationallawuniversitydelhi.in","https://nationallawuniversitydelhi.in"],
 apply:"7 Aug – 10 Nov 2026. Admit card 30 Nov.",exam:"13 Dec 2026, 2–4 PM.",fee:"₹3,000 (General/OBC/EWS), ₹1,000 (SC/ST/PwD)."},

/* MANAGEMENT */
{id:"ipmat",cat:"mgt",sort:8,n:"IPMAT Indore",full:"Integrated Programme in Management Aptitude Test",body:"IIM Indore",st:"e",
 leads:"5-year IPM at IIM Indore. Scores are also used by some other IIMs (Ranchi, Shillong, Amritsar and Sirmaur are cited).",
 elig:"Class 12, any stream.",
 pattern:"CBT, 120 minutes, 90 questions in 3 sections: Quantitative Ability (short-answer and MCQ) and Verbal Ability.",
 syl:"Quantitative ability and verbal ability.",
 portal:["iimidr.ac.in","https://www.iimidr.ac.in"],
 apply:"2026 ref: 2 Feb – 17 Mar (extended). 2027 expected Feb–Mar. The 2026 exam date was announced on 8 Oct 2025, so a 2027 announcement may come this month.",
 exam:"2026 ref: 4 May.",fee:"₹4,130 (General, 2026)."},
{id:"ipmatr",cat:"mgt",sort:10,n:"IPMAT Rohtak",full:"IIM Rohtak Integrated Programme",body:"IIM Rohtak",st:"e",
 leads:"5-year IPM at IIM Rohtak.",elig:"Class 12, any stream.",
 pattern:"Like IPMAT Indore, with an added Logical Reasoning section.",
 syl:"Quantitative ability, verbal ability and logical reasoning.",
 portal:["iimrohtak.ac.in","https://www.iimrohtak.ac.in"],
 apply:"2026 ref: 6 Feb – 6 Apr.",exam:"2026 ref: 10 May.",fee:"₹4,937 (2026)."},
{id:"jipmat",cat:"mgt",sort:14,n:"JIPMAT",full:"Joint Integrated Programme in Management Admission Test",body:"NTA",st:"e",
 leads:"IPM at IIM Bodh Gaya and IIM Jammu.",
 pattern:"See the NTA bulletin.",syl:"See the NTA bulletin.",
 portal:["exams.nta.nic.in/jipmat","https://exams.nta.nic.in/jipmat"],
 apply:"Usually in spring.",exam:"Usually Apr–Jun.",fee:"See the bulletin."},

/* COMPUTING */
{id:"iitm",cat:"comp",sort:14,n:"IIT Madras BS qualifier",full:"BS in Data Science & Applications (online)",body:"IIT Madras",st:"e",
 leads:"An IIT Madras BS degree that is online and flexible. It can be done alongside another degree.",
 elig:"Class 12 pass in any stream, with Maths and English in Class 10. Students who have completed Class 11 can apply now and join after Class 12.",
 pattern:"About 4 weeks of online coursework with graded assignments. A minimum assignment score earns the hall ticket (40% General, 35% OBC-NCL/EWS, 30% SC/ST/PwD). Then a 4-hour in-person qualifier exam with pass marks of 50%, 45% and 40%.",
 syl:"Taught in the 4-week online coursework and graded by assignments.",
 portal:["study.iitm.ac.in","https://study.iitm.ac.in"],
 apply:"Three intakes a year (January, May, September). 2026 qualifiers were held on 15 Mar and 19 Jul. The next intake is likely the January 2027 term; dates not yet seen.",
 exam:"Same cycle as above.",fee:"See the portal.",
 note:"Campus placement support is much weaker than on an on-campus degree, so build a portfolio of projects."}
);

const MINI={
eng:["More private and institute routes",[
["KIITEE","KIIT Bhubaneswar. CBT, PCM, multiple phases Apr–Jun, forms about Nov–Mar."],
["AEEE","Amrita. CBT or remote, PCM plus English and aptitude, phases about Jan and Apr. Amrita also accepts JEE Main."],
["UPESEAT","UPES Dehradun. CBT, PCM plus English and logical reasoning, multiple slots."],
["LPUNEST","Lovely Professional University. Online, home-proctored, PCM plus English, slots Nov–May. Doubles as a scholarship test."],
["Thapar (TIET), Bennett","JEE Main rank plus Class 12 marks. No separate exam for most seats."],
["Shiv Nadar, Plaksha, Ashoka","SNUSAT, Plaksha’s PSAT or Ashoka’s aptitude test, usually with an interview. Ashoka offers BSc CS, Physics and Maths, not B.Tech."],
["Chitkara","Own test, JEE or board merit."],
["SAT (College Board)","Digital, 2 h 14 min. For study abroad, and also accepted by Ashoka, Plaksha, SNU, Krea and Flame."],
["IIST Thiruvananthapuram","No separate exam. Admission on JEE Advanced rank, with the ISRO-linked B.Tech."],
["IIIT Hyderabad UGEE","Dual-degree research programmes through aptitude and research tests plus an interview, about Mar–Apr. Regular B.Tech goes through JEE Main."]]],
state:["Other states",[
["OJEE (Odisha)","Mostly lateral entry and remaining seats. B.Tech seats largely go through JEE Main."],
["GUJCET (Gujarat)","120 MCQs in PCM on the Class 12 syllabus, combined with board marks. Forms about Dec–Jan, exam Mar–Apr."],
["Assam CEE","PCM test for government engineering colleges, forms about Apr–May."],
["UP, Haryana, Rajasthan, Bihar, Punjab","Counselling runs on the JEE Main rank (UPTAC, HSTES, REAP, BCECE/UGEAC, IKGPTU). No separate test, so take both JEE Main sessions."]]],
def:["Other uniformed and maritime routes",[
["Army 10+2 Technical Entry (TES)","PCM at about 60% (verify). Shortlisted on JEE Main score, then SSB. Leads to a B.Tech and commission. Two intakes a year."],
["Air Force officer","For 10+2 students the only officer route is the NDA Air Force wing."],
["Agniveer, Navy Agniveer, Coast Guard Navik","Enlisted, non-officer roles. Multiple notifications each year."],
["CDS (UPSC)","Graduates only. A later option after your degree."],
["IMU-CET (Merchant Navy)","Marine engineering, nautical science and more. PCM about 60% and English about 50% (verify). Strict medical and eyesight standards. Applications about Mar–May, test May–Jun."]]],
sci:["Scholarships and other science routes",[
["INSPIRE-SHE","₹80,000 a year for top-1-percentile Class 12 students or JEE/NEET rank holders in basic sciences. Applications open after board results on online-inspire.gov.in. It replaces KVPY, which ended after 2022."],
["IIT JAM","For M.Sc. after graduation. A future step."],
["NCHM JEE","Hotel management, open to any stream. Usually an April CBT."],
["IGRUA, Amethi","Pilot training. Class 12 with Physics and Maths, DGCA medical, written test, aptitude test and interview. Fees run to tens of lakhs."],
["NPTI","B.Tech in Power Engineering through JEE Main or state counselling."]]],
des:["Related routes",[
["JEE Main Paper 2A and 2B","B.Arch (2A) and B.Planning (2B) at NITs and SPAs. Maths, aptitude and drawing or planning. Held with Sessions 1 and 2."],
["CEED","M.Des. Postgraduate only."],
["Pearl, MIT-ID, Symbiosis SEED, WUD, UID","Own aptitude tests plus portfolio or interview, Nov–May, with rolling deadlines."]]],
law:["Other law routes",[
["LSAT-India","Reported discontinued for India. Verify before planning."],
["SLAT, MH CET Law","Rolling, about Mar–Jun. Check each portal."]]],
mgt:["Other management routes",[
["NPAT (NMIMS), SET (Symbiosis), Christ University","BBA, BMS and economics-type programmes with rolling windows from about December to May."],
["CUET-UG","DU’s BMS, BBA (FIA) and BBE run through CUET. DU JAT no longer exists."]]],
comp:["Other computing routes",[
["Other IIT online BS programmes","Own qualifier or JEE-based entry. Check each IIT’s portal."],
["Scaler School of Technology (NSET)","Maths and logical reasoning test plus an interview. Check the degree-granting university and UGC recognition first."],
["Newton School of Technology (NSAT)","Own aptitude test plus an interview. Same checks apply."],
["Masai and similar bootcamps","Aptitude and communication tests. Skill programmes, not a formal degree in most tracks."]]]
};
const CORE={
Physics:[["",["Units and measurement","Kinematics","Laws of motion","Work, energy, power","Rotational motion","Gravitation","Properties of solids and liquids","Thermodynamics","Kinetic theory","Oscillations and waves","Electrostatics","Current electricity","Magnetic effects and magnetism","EMI and AC","Electromagnetic waves","Ray and wave optics","Dual nature of matter","Atoms and nuclei","Semiconductor electronics","Experimental skills"]]],
Chemistry:[["Physical",["Mole concept","Atomic structure","Chemical bonding","Thermodynamics","Equilibrium","Redox and electrochemistry","Chemical kinetics","Solutions"]],["Inorganic",["Periodicity","p-block","d- and f-block","Coordination compounds"]],["Organic",["General organic chemistry","Hydrocarbons","Haloalkanes and haloarenes","Alcohols, phenols, ethers","Aldehydes, ketones, acids","Amines","Biomolecules","Practical chemistry"]]],
Mathematics:[["",["Sets, relations, functions","Complex numbers and quadratics","Matrices and determinants","Permutations and combinations","Binomial theorem","Sequences and series","Limits, continuity, differentiability","Integrals","Differential equations","Straight lines, circles, conics","3D geometry","Vectors","Statistics and probability","Trigonometry"]]]
};

/* columns: Physics, Chemistry, Maths, Biology, English, Reasoning or aptitude, GK or current affairs, Drawing or design */
const MXC=["Physics","Chemistry","Maths","Biology","English","Reasoning","GK","Drawing"];
const MX=[
["BITSAT",[1,1,1,0,1,1,0,0]],["VITEEE",[1,1,1,0,1,1,0,0]],["SRMJEEE",[1,1,1,0,1,1,0,0]],["MET",[1,1,1,0,1,1,0,0]],["COMEDK",[1,1,1,0,0,0,0,0]],
["State CETs (MHT, KCET, WBJEE, EAPCET, KEAM)",[1,1,1,0,0,0,0,0]],["NDA & NA",[0,0,1,0,1,0,1,0]],["IISER IAT",[1,1,1,1,0,0,0,0]],["NEST",[1,1,1,1,0,0,0,0]],
["ISI, CMI",[0,0,1,0,0,0,0,0]],["CUET-UG (PCM + General Test)",[1,1,1,0,1,1,1,0]],["NATA",[1,0,1,0,0,1,0,1]],["UCEED",[0,0,0,0,1,1,0,1]],
["NID DAT",[0,0,0,0,0,1,0,1]],["NIFT",[0,0,0,0,1,1,1,1]],["CLAT",[0,0,0,0,1,1,1,0]],["AILET",[0,0,0,0,1,1,1,0]],["IPMAT",[0,0,1,0,1,1,0,0]]
];

const CAR={
eng:{t:"Engineering",s:"BITSAT, VITEEE, SRMJEEE, MET, COMEDK, state CETs",
 f:"Software and IT, AI and data science, electronics and semiconductors, mechanical and automotive, civil and infrastructure, chemical and energy.",
 jobs:[["IT services (TCS, Infosys, Wipro)","₹3.5–7 LPA"],["Product companies and top startups","₹15–45 LPA+"],["Core firms (L&T, Bosch, Siemens, Tata Motors)","₹4–10 LPA"],["PSUs via GATE (BHEL, ONGC, NTPC, IOCL)","₹12–18 LPA CTC"]],
 g:"M.Tech through GATE, an MS abroad, an MBA through CAT, or your own startup. Average packages: BITS about ₹18–30 LPA, VIT/SRM/Manipal about ₹6–10 LPA (top 10–15% at ₹15–40 LPA), other colleges ₹3–8 LPA.",
 r:"Branch and skills matter as much as the college. CSE at an average college often beats Mechanical at a famous one.",
 ex:["bitsat","viteee","srm","met","comedk","mht"]},
def:{t:"Defence officer",s:"NDA, Navy 10+2 B.Tech, Army TES",
 f:"Army (infantry, armoured, artillery, engineers, signals, EME), Navy (executive, engineering, electrical), Air Force (flying, technical, ground duties).",
 jobs:[["Starting officer pay incl. allowances","₹1–1.3 lakh a month"],["Perks","Free education, pension, medical, canteen"],["Rank path","Captain, Major, Lt Col, Colonel"],["After retirement","Corporate security, aviation, PSUs, teaching"]],
 g:"NDA gives 3 years at the academy plus 1 year of specialised training, then you join as Lieutenant, Sub-Lieutenant or Flying Officer. Rank, not market demand, sets your pay.",
 r:"SSB selection rates are low. Postings can be remote, and eyesight and medical standards are strict.",
 ex:["nda","navy"]},
res:{t:"Research and pure science",s:"IISER IAT, NEST, ISI, CMI",
 f:"Physics, chemistry, maths, biology, statistics, data science, computer science.",
 jobs:[["PhD stipend","₹37,000–42,000 a month"],["Faculty at IITs and IISERs","₹1.5–2.5 lakh a month"],["Quant and data roles (ISI, CMI)","₹15–40 LPA"],["Government research","ISRO, DRDO, BARC, CSIR"],["Industry R&D","Pharma, materials, semiconductors, energy"]],
 g:"A PhD in India or abroad, then professor. Many PhDs abroad are fully funded. Other exits: science policy, journalism, civil services.",
 r:"The path is long, since a PhD takes 5–6 years after your degree. It suits students who love the subject.",
 ex:["iat","nest","isi","cmi","cuet"]},
des:{t:"Architecture and design",s:"NATA, UCEED, NID, NIFT",
 f:"Architecture (5-year B.Arch), product, UX and industrial design, animation and games, fashion and textiles.",
 jobs:[["Architect, planner, interior designer","₹2.5–6 LPA"],["UX, product, industrial designer (IIT, NID)","₹8–25 LPA"],["Fashion and retail (NIFT)","₹4–8 LPA"],["Employers","Google, Microsoft, Flipkart, Swiggy, Titan, Tata, Reliance, Raymond, Myntra"]],
 g:"Architecture pay grows slowly and is highest with your own practice. UX design is strongly tied to the tech industry.",
 r:"Architecture needs Physics and Maths in Class 12. Design exams accept any stream, so portfolio and sketching practice decide the outcome.",
 ex:["uceed","nid","nift","nata"]},
law:{t:"Law",s:"CLAT, AILET",
 f:"Corporate law, litigation, in-house counsel, policy, civil services, LLM abroad, teaching, judiciary through state judicial service exams.",
 jobs:[["Top corporate law firms","₹15–25 LPA"],["Litigation, early years","₹2–5 LPA"],["Judiciary","State judicial exams, usually after some years of practice"],["PCM niche","Patent, IP and tech law"]],
 g:"Litigation starts low and rewards seniority, with potentially high pay after 8–10 years.",
 r:"Top firms ask for long hours. Pay depends heavily on the NLU and the firm.",
 ex:["clat","ailet"]},
mgt:{t:"Management and economics",s:"IPMAT, JIPMAT, CUET",
 f:"Consulting, finance, product management, marketing, analytics, banking, policy, think tanks, RBI.",
 jobs:[["IPM at IIM Indore or Rohtak (5-year BBA + MBA)","₹20–30 LPA reported"],["DU BMS, BBA or Economics via CUET","₹5–10 LPA"],["Growth","Better with an MBA"]],
 g:"IPM gives a management degree in 5 years. DU routes improve with an MBA later.",
 r:"IPM seats are few and the exam is competitive. Maths is often mandatory for DU Economics.",
 ex:["ipmat","ipmatr","jipmat","cuet"]},
comp:{t:"Computing and data science",s:"IIT Madras BS, Scaler, Newton",
 f:"Data analyst, ML engineer, software developer.",
 jobs:[["Starting pay","₹5–15 LPA"],["Depends on","Skills and projects"]],
 g:"The IIT Madras BS is online and flexible, so it pairs well with another degree.",
 r:"Campus placement support is weaker than on-campus degrees. For the private tech schools, check the degree-granting university and verify placement claims, which come from the schools themselves.",
 ex:["iitm","bitsat","mht"]},
avi:{t:"Aviation and Merchant Navy",s:"IGRUA, DGCA CPL, IMU-CET",
 f:"Airline pilot, marine engineer, deck officer.",
 jobs:[["Airline first officer","₹1–2 lakh a month"],["Captain","₹4–8 lakh a month or more"],["Marine trainee, early years","₹50,000–1 lakh a month"],["Senior marine officer","Several lakh a month"]],
 g:"Pilot training costs ₹50–80 lakh. Seafarers often get tax benefits.",
 r:"A strict Class 1 medical and cyclical airline hiring. Merchant Navy contracts run 4–6 months away from family.",
 ex:[]}
};

/* lo and hi in lakh per year, domain 0 to 45 */
const PAY=[
["eng","IT services",3.5,7],["eng","Core firms",4,10],["eng","VIT, SRM, Manipal average",6,10],["eng","PSUs via GATE",12,18],["eng","BITS Pilani average",18,30],["eng","Product firms, top startups",15,45],
["def","Lieutenant, with allowances",12,15.6],
["res","PhD stipend",4.4,5],["res","ISI and CMI quant, data roles",15,40],
["des","Architect",2.5,6],["des","NIFT fashion and retail",4,8],["des","IIT and NID design",8,25],
["law","Litigation, early years",2,5],["law","Top law firms",15,25],
["mgt","DU BMS, BBA, Economics",5,10],["mgt","IPM at an IIM",20,30],
["comp","Computing BS and tech schools",5,15],
["avi","Marine trainee, early years",6,12],["avi","Airline first officer",12,24]
];

const QZ=[
{q:"Pick the task you would happily do for three hours.",o:[["Debug code or wire a circuit",{eng:2,comp:2}],["Work through a physics or maths puzzle",{res:3}],["Sketch a building, a chair or an app screen",{des:3}],["Build an argument or read a policy",{law:2,mgt:2}],["Train hard and lead a team under pressure",{def:3,avi:1}]]},
{q:"Ten years from now, what do you want most?",o:[["Pay that grows quickly",{eng:1,mgt:2,comp:2,law:1}],["Stability and respect",{def:2,res:1,law:1}],["Work that is mine and visibly creative",{des:3}],["Original research with my name on it",{res:3}],["Adventure and a job that moves",{avi:2,def:1}]]},
{q:"How do you feel about the length of the road?",o:[["Fine with 5 or more years of study",{res:2,law:2,mgt:1}],["Four years, then I work",{eng:2,comp:2,des:1}],["I want paid training from day one",{def:3}],["A big upfront cost is fine if the payoff is fast",{avi:3,mgt:1}]]}
];
const PATHS={
eng:{ids:["bitsat","viteee","comedk"],set:"JEE Main and Advanced, BITSAT (both sessions), your home-state CET, plus one or two of VITEEE, MET or COMEDK.",now:"Watch for JEE Main registration (expected in the last week of Oct) and the VITEEE and MET forms."},
def:{ids:["nda"],set:"NDA (I) 2027 and NDA (II) 2027. Take JEE Main too, since the Navy 10+2 B.Tech and Army TES use it.",now:"NDA (I) forms run 2–22 Dec 2026. Start Maths and GAT practice by November."},
res:{ids:["iat","nest","isi"],set:"IISER IAT and NEST in June, ISI and CMI if you enjoy proof-style maths, and CUET with Physics, Chemistry and Maths.",now:"Revise Biology basics before May. Watch for the ISI test date, usually announced in late December."},
des:{ids:["uceed","nid","nift","nata"],set:"UCEED, NID DAT and NIFT for design. NATA and JEE Main Paper 2A for architecture.",now:"UCEED closes 31 Oct and NID DAT closes 30 Nov. Decide this month."},
law:{ids:["clat","ailet"],set:"CLAT and AILET, then SLAT or MH CET Law if you want more options.",now:"CLAT closes 31 Oct and AILET closes 10 Nov."},
mgt:{ids:["ipmat","ipmatr"],set:"IPMAT Indore and Rohtak, JIPMAT, and CUET with Maths and the General Test. Add NPAT, SET or Christ if you want more.",now:"Forms open Feb–Mar. Watch for the IPMAT date announcement, which came in October last year."},
comp:{ids:["iitm","bitsat"],set:"JEE Main, BITSAT and your state CET, plus the IIT Madras BS qualifier as an add-on.",now:"The IIT Madras qualifier can be attempted in early 2027 without disturbing JEE preparation."},
avi:{ids:[],set:"IGRUA or the DGCA CPL route for flying, IMU-CET for the Merchant Navy. Keep JEE as a backup.",now:"Book the DGCA Class 2 medical first. It decides whether this route is open to you."}
};

const GOALS=[
["Top engineering colleges","JEE Main and Advanced, BITSAT (both sessions), home-state CET","VITEEE, MET, COMEDK, SRMJEEE as safety, KIITEE","Too many low-tier private tests. Each costs ₹1,000–2,000 and a weekend."],
["Defence officer","NDA (I) and (II) 2027","JEE Main for Navy B.Tech (Jan 2028 course) and Army TES","CDS (graduates only)"],
["Research and pure science","IISER IAT, NEST, CUET (Physics, Chemistry, Maths)","ISI and CMI if strong in maths; JEE Advanced for IISc BS and IIT BS courses","None"],
["Mathematics and statistics","ISI (B.Stat, B.Math), CMI","IAT (Economic & Statistical Sciences, Tirupati), CUET (DU Maths and Stats)","None"],
["Architecture","NATA and JEE Main Paper 2A","State B.Arch counselling","None"],
["Design","UCEED (by 31 Oct), NID DAT (by 30 Nov), NIFT","Pearl, MIT-ID, Symbiosis SEED","CEED (postgraduate only)"],
["Management and economics","IPMAT Indore and Rohtak, CUET (Maths and General Test)","JIPMAT, NPAT, SET, Christ","DU JAT (no longer exists)"],
["Law","CLAT (by 31 Oct), AILET (by 10 Nov)","SLAT, MH CET Law","LSAT-India (verify status)"],
["Computing and data science","JEE Main, BITSAT, state CET","IIT Madras BS qualifier; Scaler or Newton only after due diligence","Unaccredited bootcamps as the only option"]
];
const STEPS=[
"Core engineering set: JEE Main (both sessions), JEE Advanced, BITSAT, your home-state CET, and one or two of VITEEE, MET or COMEDK. They share the PCM syllabus. BITSAT needs 2–3 extra weeks of English and logical reasoning.",
"Science-curious add-on: IISER IAT and NEST in June. The only extra work is Biology basics in May. Add ISI and CMI if you enjoy proof-style maths.",
"Defence-curious add-on: NDA (I) 2027, apply by 22 Dec 2026, then NDA (II). Little extra Maths is needed. Budget 4–6 weeks for the GAT.",
"Hedge for other interests: CUET-UG keeps DU, BHU and central-university BSc, economics and BMS open. Add IPMAT if management appeals.",
"Creative or law interest: decide this month. UCEED and CLAT close 31 Oct, AILET 10 Nov, NID 30 Nov.",
"Cap the list at 8 to 10 exams. Beyond that, travel and exam fatigue in April–June start to hurt JEE and board performance."
];
const TRAPS=[
"<b>Navy 10+2 B.Tech.</b> It uses the previous year’s JEE Main rank. A 2027 Class 12 student applies for the Jan 2028 course, notified around May–Jun 2027.",
"<b>Exams that no longer exist.</b> ICAR AIEEA-UG, DU JAT and KVPY are not separate exams now. CUET covers the first two. INSPIRE-SHE replaces KVPY.",
"<b>Graduate-only exams.</b> CEED, IIT JAM and CDS are for after your degree.",
"<b>Conflicting dates online.</b> Several sites already show exact 2027 dates for BITSAT, COMEDK and MET. None are official. Only the conducting body’s portal counts.",
"<b>IAT needs Biology.</b> All four sections must be attempted, so PCM students should revise Class 11–12 Biology basics."
];
const SOURCES=[
["JEE Main","jeemain.nta.nic.in","https://jeemain.nta.nic.in"],["BITSAT","bitsadmission.com","https://bitsadmission.com"],["VITEEE","viteee.vit.ac.in","https://viteee.vit.ac.in"],
["SRMJEEE","srmist.edu.in","https://www.srmist.edu.in"],["MET","manipal.edu","https://www.manipal.edu"],["COMEDK","comedk.org","https://www.comedk.org"],
["MHT CET","cetcell.mahacet.org","https://cetcell.mahacet.org"],["KCET","cetonline.karnataka.gov.in/kea","https://cetonline.karnataka.gov.in/kea"],["WBJEE","wbjeeb.nic.in","https://wbjeeb.nic.in"],
["AP EAPCET","cets.apsche.ap.gov.in","https://cets.apsche.ap.gov.in"],["TG EAPCET","eapcet.tgche.ac.in","https://eapcet.tgche.ac.in"],["KEAM","cee.kerala.gov.in","https://cee.kerala.gov.in"],
["NDA & NA, CDS","upsc.gov.in","https://upsc.gov.in"],["Indian Navy","joinindiannavy.gov.in","https://www.joinindiannavy.gov.in"],["IISER IAT","iiseradmission.in","https://www.iiseradmission.in"],
["NEST","nestexam.in","https://www.nestexam.in"],["ISI","admission.isical.ac.in","https://admission.isical.ac.in"],["CMI","cmi.ac.in","https://www.cmi.ac.in"],
["CUET-UG","cuet.nta.nic.in","https://cuet.nta.nic.in"],["NATA","nata.in","https://www.nata.in"],["UCEED","uceed.iitb.ac.in","https://www.uceed.iitb.ac.in"],
["NID DAT","admissions.nid.edu","https://admissions.nid.edu"],["NIFT","exams.nta.nic.in/niftee","https://exams.nta.nic.in/niftee"],["CLAT","consortiumofnlus.ac.in","https://consortiumofnlus.ac.in"],
["AILET","nationallawuniversitydelhi.in","https://nationallawuniversitydelhi.in"],["IPMAT Indore","iimidr.ac.in","https://www.iimidr.ac.in"],["IPMAT Rohtak","iimrohtak.ac.in","https://www.iimrohtak.ac.in"],
["JIPMAT","exams.nta.nic.in/jipmat","https://exams.nta.nic.in/jipmat"],["IIT Madras BS","study.iitm.ac.in","https://study.iitm.ac.in"],["INSPIRE-SHE","online-inspire.gov.in","https://online-inspire.gov.in"]
];
